image: "rust:latest"

lint:clippy:
    before_script:
        - rustup component add clippy
    script: cargo clippy -- --deny warnings

test:debug:
    script: cargo test --all-targets --all-features

test:release:
    script: cargo test --all-features --release
