[package]
name = "ws2300"
version = "1.0.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"

[dependencies]
serial = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.clap]
version = "4.0"
features = ["derive"]
