on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_fmt:
    name: cargo fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Check formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  lint_clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- --deny warnings

  tests:
    name: Tests
    strategy:
      matrix:
        mode: ["debug", "release"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests (debug)
        if: matrix.mode == 'debug'
        run: cargo test --all-features

      - name: Run tests (release)
        if: matrix.mode == 'release'
        run: cargo test --all-features --release
